name: autocommit

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
